name: Deploy container app
description: 'Deploy a container app and associated resources to azure'
inputs:
  subscription:
    description: The subscription to add the resource group to
    required: true
  subscription-id:
    description: The id of the subscription to add the resource group to
    required: true
  environment:
    description: The environment being deployed to
    required: true
  environment-resource-group-name:
    description: The default resource group for the environment being deployed to
    required: true
  revision-suffix:
    description: The revision suffix for the container app
    required: true
  resource-group-name:
    description: The name of the resource group to deploy associated resources to where possible.
    required: true
  resource-group-exists:
    description: The name of the resource group to deploy associated resources to where possible.
    required: true
  container-app-environment-name:
    description: The resource name for the container app environment.
    required: true
  container-app-name:
    description: The resource name for the container app.
    required: true
  container-app-exists:
    description: Whether the container app currently exists
    required: true
  sql-database-name:
    description: The resource name for the sql database.
    required: true
  sql-database-exists:
    description: Whether the sql database currently exists
    required: true
  ghcr-username:
    description: The username to use for pulling from ghcr
    required: true
  ghcr-token:
    description: The token to use for pulling from ghcr
    required: true

runs:
  using: "composite"
  steps:
  - name: get-container-app-principal-id
    id: container-app-principal-id
    shell: bash
    run: |
      principalId="$(az containerapp show --name ${{ inputs.container-app-name }} -g ${{ inputs.resource-group-name }} --query 'identity.principalId')"
      echo "$principalId"
      echo "principal-id=$principalId" >> $GITHUB_OUTPUT

  - name: ensure-sql-database-exists
    if: ${{ inputs.sql-database-exists == 0 }}
    uses: azure/bicep-deploy@v2
    with:
      type: deployment
      operation: create
      name: deploy-new-sql-database
      scope: resourceGroup
      subscription-id: ${{ inputs.subscription-id }}
      resource-group-name: rg-dev-tag
      template-file: ./.github/workflows/bicep/create-database.bicep
      parameters: |
        environment_resource_group_name: ${{ inputs.environment-resource-group-name }}
        database_name: ${{ inputs.sql-database-name }}
        server_name: ${{ inputs.environment }}-tag
        container_app_principal_id: ${{ steps.container-app-principal-id.outputs.principal-id }}

  - name: ensure-container-app-access
    if: ${{ inputs.sql-database-exists == 0 }}
    uses: azure/sql-action@v2.3
    with:
      connection-string: "Server=tcp:dev-tag.database.windows.net,1433;Initial Catalog=${{ inputs.sql-database-name }};Authentication=Active Directory Default;Encrypt=True;"
      path: ./.github/workflows/initialize-user.sql
      arguments: '-v CaName=${{ inputs.container-app-name }}'
