name: Deploy container app
description: 'Deploy a container app and associated resources to azure'
inputs:
  subscription:
    description: The subscription to add the resource group to
    required: true
  subscription-id:
    description: The id of the subscription to add the resource group to
    required: true
  environment:
    description: The environment being deployed to
    required: true
  revision-suffix:
    description: The revision suffix for the container app
    required: true
  resource-group-name:
    description: The name of the resource group to deploy associated resources to where possible.
    required: true
  resource-group-exists:
    description: The name of the resource group to deploy associated resources to where possible.
    required: true
  container-app-environment-name:
    description: The resource name for the container app environment.
    required: true
  container-app-name:
    description: The resource name for the container app.
    required: true
  container-app-exists:
    description: Whether the container app currently exists
    required: true
  sql-database-name:
    description: The resource name for the sql database.
    required: true
  sql-database-exists:
    description: Whether the sql database currently exists
    required: true
  gh-token:
    description: Github Token
    required: true

runs:
  using: "composite"
  steps:
  - name: ensure-resource-group
    if: ${{ inputs.resource-group-exists == 0 }}
    shell: bash
    run: |
      az group create -n ${{ inputs.resource-group-name }} -l uksouth --subscription ${{ inputs.subscription }}

  - name: get-container-app-environment-id
    id: container-app-environment-id
    shell: bash
    run: |
      caeId="$(az containerapp env list -g rg-dev-tag --query '[?name==`'${{ inputs.container-app-environment-name }}'`].id | [0]')"
      echo "$caeId"
      echo "cae-id=$caeId" >> $GITHUB_OUTPUT

  - name: ensure-container-app-exists
    if: ${{ inputs.container-app-exists == 0 }}
    uses: azure/bicep-deploy@v2
    with:
      type: deployment
      operation: create
      name: deploy-database
      scope: resourceGroup
      subscription-id: ${{ inputs.subscription-id }}
      resource-group-name: ${{ inputs.resource-group-name }}
      template-file: ./.github/workflows/bicep/create-empty-container-app.bicep
      parameters: |
        container_app_environment_id: ${{ steps.container-app-environment-id.outputs.cae-id }}
        container_app_name: ${{ inputs.container-app-name }}
        ghcr_password: ${{ github.token }}
