name: Deploy container app
description: 'Deploy a container app and associated resources to azure'

runs:
  using: "composite"
  steps:
  - name: ensure-resource-group
    if: ${{ env.resource-group-exists == 0 }}
    shell: bash
    run: |
      az group create -n ${{ env.resource-group-name }} -l uksouth --subscription ${{ env.subscription }}

  - name: get-container-app-required-variables
    id: container-app-required-variables
    shell: bash
    run: |
      caeId="$(az containerapp env list -g ${{ env.environment-resource-group-name }} --query '[?name==`'${{ env.container-app-environment-name }}'`].id | [0]')"
      echo "$caeId"
      echo "cae-id=$caeId" >> $GITHUB_OUTPUT

  - name: ensure-container-app-exists
    if: ${{ env.container-app-exists == 0 }}
    uses: azure/bicep-deploy@v2
    with:
      type: deployment
      operation: create
      name: deploy-empty-container-app
      scope: resourceGroup
      subscription-id: ${{ env.subscription-id }}
      resource-group-name: ${{ env.resource-group-name }}
      template-file: ./.github/workflows/bicep/create-empty-container-app.bicep
      parameters: |
        environment: ${{ env.environment-name }}
        environment_resource_group_name: ${{ env.environment-resource-group-name }}
        container_app_environment_id: ${{ steps.container-app-required-variables.outputs.cae-id }}
        container_app_name: ${{ env.container-app-name }}
        app_insights_name: ${{ env.app-insights-name }}
        app_insights_exists: ${{ env.app-insights-exists }}
        log_analytics_workspace_name: ${{ env.log-analytics-workspace-name }}
        ghcr_username: ${{ env.ghcr-username }}
        ghcr_token: ${{ env.ghcr-token }}

  - name: get-container-app-principal-id
    id: container-app-principal-id
    shell: bash
    run: |
      principalId="$(az containerapp show --name ${{ env.container-app-name }} -g ${{ env.resource-group-name }} --query 'identity.principalId')"
      echo "$principalId"
      echo "principal-id=$principalId" >> $GITHUB_OUTPUT

  - name: ensure-sql-database-exists
    if: ${{ env.sql-database-exists == 0 }}
    uses: azure/bicep-deploy@v2
    with:
      type: deployment
      operation: create
      name: deploy-new-sql-database
      scope: resourceGroup
      subscription-id: ${{ env.subscription-id }}
      resource-group-name: ${{ env.environment-resource-group-name }}
      template-file: ./.github/workflows/bicep/create-database.bicep
      parameters: |
        environment_resource_group_name: ${{ env.environment-resource-group-name }}
        database_name: ${{ env.sql-database-name }}
        server_name: ${{ env.sql-server-name }}
        container_app_principal_id: ${{ steps.container-app-principal-id.outputs.principal-id }}

  - name: ensure-container-app-access
    if: ${{ env.sql-database-exists == 0 }}
    uses: azure/sql-action@v2.3
    with:
      connection-string: "Server=tcp:${{ env.sql-server-name }}.database.windows.net,1433;Initial Catalog=${{ env.sql-database-name }};Authentication=Active Directory Default;Encrypt=True;"
      path: ./.github/workflows/initialize-user.sql
      arguments: '-v CaName=${{ env.container-app-name }}'

  - name: deploy-container-app-revision
    uses: azure/arm-deploy@v2
    with:
      resourceGroupName: ${{ env.resource-group-name }}
      template: ./.github/workflows/bicep/create-container-app-revision.bicep
      deploymentName: 'deploy-container-app-revision ${{ env.revision-suffix }}'
      scope: resourcegroup
      parameters: |
        app_config_name='app-config-${{ env.environment-name }}-tag'
        app_insights_name=${{ env.app-insights-name }}
        container_app_name=${{ env.container-app-name }}
        container_app_image_name=${{ env.service-name }}
        container_app_image_tag=${{ env.version-no }}
        cpu='0.5'
        environment_resource_group_name=${{ env.environment-resource-group-name }}
        memory='1Gi'
        min_replicas=1
        max_replicas=1
        database_connection_string='Server=tcp:${{ env.sql-server-name }}.database.windows.net,1433;Authentication="Active Directory Managed Identity";Encrypt=True;Database=${{ env.sql-database-name }}'
        container_app_environment_id=${{ steps.container-app-required-variables.outputs.cae-id }}
        ghcr_username=${{ env.ghcr-username }}
        ghcr_token=${{ env.ghcr-token }}

  - name: get-dependency-configuration-details
    id: dependency-configuration
    shell: bash
    run: |
      appInsightsConnectionString="$(az monitor app-insights component show --query '[?name==`'${{ env.app-insights-name }}'`].connectionString | [0]')"
      echo "app-insights-connection-string=$appInsightsConnectionString" >> $GITHUB_OUTPUT
