name: Test deployment playground pipeline.

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy-container-app:
    environment: dev
    name: Test stuff
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: azure/login@v3
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - id: get-connection-string
      run: |
        anonymisedIntegratedAuthConnectionString="$(az sql db show-connection-string --subscription sub-tag-testing -s dev-tag -n sql-ca-traveller-svc-dev-prd-336 -c ado.net)"
        echo "$anonymisedIntegratedAuthConnectionString"
        integratedAuthConnectionString=${anonymisedIntegratedAuthConnectionString/<username>/sming-entra}
        echo "$integratedAuthConnectionString"

        echo "connection-string=$integratedAuthConnectionString" >> $GITHUB_OUTPUT

    - uses: azure/sql-action@v2.3
      with:
        connection-string: "Server=tcp:dev-tag.database.windows.net,1433;Initial Catalog=sql-ca-traveller-svc-dev-prd-336;Persist Security Info=False;User ID=mi-dev-tag-sql;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Authentication='Active Directory Integrated';"
        path: ./.github/workflows/initialize-user.sql
        # arguments: '-v CaName=ca-traveller-svc-dev-prd-336'
