name: Deploy container app to environments

on:
  workflow_call:
    inputs:
      logical-area:
        description: The logical area to deploy to
        required: true
        type: string
      app-name:
        description: The name of the app
        required: true
        type: string
      service-name:
        description: The service name to use for logging
        required: true
        type: string
      version-no:
        description: The version number of the container image
        required: true
        type: string
      environments:
        description: The environments to deploy to
        required: true
        type: string
      service-types:
        description: The service types to deploy
        required: true
        type: string
    secrets: 
      ghcr-username:
        required: true
      ghcr-token:
        required: true
      client-id-dev:
        required: true
      client-id-test:
        required: true
      client-id-prod:
        required: true
      tenant-id-dev:
        required: true
      tenant-id-test:
        required: true
      tenant-id-prod:
        required: true
      subscription-id-dev:
        required: true
      subscription-id-test:
        required: true
      subscription-id-prod:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy-to-environments:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        environment: ${{ fromJson(inputs.environments) }}
        service-type: ${{ fromJson(inputs.service-types) }}
      max-parallel: 1
    environment: ${{ matrix.environment }}
    steps:
    - uses: actions/checkout@v6

    - uses: azure/login@v3
      with:
        client-id: ${{ case(matrix.environment == 'dev', secrets.client-id-dev, case(matrix.environment == 'test', secrets.client-id-test, case(matrix.environment == 'prod', secrets.client-id-prod, 'unknown'))) }}
        tenant-id: ${{ case(matrix.environment == 'dev', secrets.tenant-id-dev, case(matrix.environment == 'test', secrets.tenant-id-test, case(matrix.environment == 'prod', secrets.tenant-id-prod, 'unknown'))) }}
        subscription-id: ${{ case(matrix.environment == 'dev', secrets.subscription-id-dev, case(matrix.environment == 'test', secrets.subscription-id-test, case(matrix.environment == 'prod', secrets.subscription-id-prod, 'unknown'))) }}

    - name: Generate container app variables
      id: ca-variables
      uses: ./.github/actions/get-ca-variables
      with:
        environment: ${{ matrix.environment }}
        app-name: ${{ inputs.app-name }}
        logical-area: ${{ inputs.logical-area }}

    - id: output-test
      run: |
        echo "${{ steps.ca-variables.outputs.resource-group-name }}"
        echo "${{ steps.ca-variables.outputs.resource-group-exists }}"
        echo "${{ steps.ca-variables.outputs.container-app-environment-name }}"
        echo "${{ steps.ca-variables.outputs.container-app-name }}"
        echo "${{ steps.ca-variables.outputs.container-app-exists }}"
        echo "${{ steps.ca-variables.outputs.app-insights-name }}"
        echo "${{ steps.ca-variables.outputs.app-insights-exists }}"
        echo "${{ steps.ca-variables.outputs.sql-server-name }}"
        echo "${{ steps.ca-variables.outputs.sql-database-name }}"
        echo "${{ steps.ca-variables.outputs.sql-database-exists }}"
        echo "${{ steps.ca-variables.outputs.environment-resource-group-name }}"

    - uses: ./.github/actions/deploy-container-app
      env:
        logical-area: ${{ inputs.logical-area }}
        app-name: ${{ inputs.app-name }}
        service-name: ${{ inputs.service-name }}
        environment-name: ${{ matrix.environment }}
        version-no: ${{ inputs.version-no }}
        subscription: ${{ case(matrix.environment == 'dev', 'sub-tag-testing', case(matrix.environment == 'test', 'sub-tag-testing', case(matrix.environment == 'prod', 'sub-tag-testing', 'unknown'))) }}
        subscription-id: ${{ case(matrix.environment == 'dev', secrets.subscription-id-dev, case(matrix.environment == 'test', secrets.subscription-id-test, case(matrix.environment == 'prod', secrets.subscription-id-prod, 'unknown'))) }}
        environment-resource-group-name: ${{ steps.ca-variables.outputs.environment-resource-group-name }}
        revision-suffix: ${{ inputs.version-no }}
        resource-group-name: ${{ steps.ca-variables.outputs.resource-group-name }}
        resource-group-exists: ${{ steps.ca-variables.outputs.resource-group-exists }}
        container-app-environment-name: ${{ steps.ca-variables.outputs.container-app-environment-name }}
        container-app-name: ${{ steps.ca-variables.outputs.container-app-name }}
        container-app-exists: ${{ steps.ca-variables.outputs.container-app-exists }}
        app-insights-name: ${{ steps.ca-variables.outputs.app-insights-name }}
        app-insights-exists: ${{ steps.ca-variables.outputs.app-insights-exists }}
        sql-server-name: ${{ steps.ca-variables.outputs.sql-server-name }}
        sql-database-name: ${{ steps.ca-variables.outputs.sql-database-name }}
        sql-database-exists: ${{ steps.ca-variables.outputs.sql-database-exists }}
        log-analytics-workspace-name: ${{ steps.ca-variables.outputs.log-analytics-workspace-name }}
        ghcr-username: ${{ secrets.ghcr-username }}
        ghcr-token: ${{ secrets.ghcr-token }}
