name: Test deployment pipeline.

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy-to-dev:
        description: 'Deploy branch container to dev environment for testing'
        required: false
        type: boolean
        default: false

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  logical-area: private
  app-name: traveller
  service-name: "Traveller Service"
  service-types: '["Api"]'

jobs:
  variables:
    name: Generate variables
    runs-on: ubuntu-latest
    steps:
    - uses: sming-code/get-version-no-action@v1
      id: get-version
      with:
        major: 1
        minor: 0
    - name: Display done
      run: echo "Variables loaded..."
    outputs:
      version-no: ${{ steps.get-version.outputs.version-no }}
      last-release-tag: ${{ steps.get-version.outputs.last-release-tag }}
      branch-deploy-environments: '["dev"]'
      environments: '["dev","test","prod"]'

  deployments:
    name: Deploy container app and related resources to environments
    needs: [ variables ]
    if: ${{ (github.ref == 'refs/heads/main') || (inputs.deploy-to-dev == true) }}
    uses: ./.github/workflows/deploy-container-app.yaml
    with:
      version-no: ${{ needs.variables.outputs.version-no }}
      environments: ${{ case(github.ref == 'refs/heads/main', needs.variables.outputs.environments, needs.variables.outputs.branch-deploy-environments) }}
      service-types: "$service-types"
    secrets:
      ghcr-username: ${{ secrets.GHCR_USERNAME }}
      ghcr-token: ${{ secrets.GHCR_TOKEN }}
      client-id-dev: ${{ secrets.AZURE_CLIENT_ID_DEV }}
      client-id-test: ${{ secrets.AZURE_CLIENT_ID_TEST }}
      client-id-prod: ${{ secrets.AZURE_CLIENT_ID_PROD }}
      tenant-id-dev: ${{ secrets.AZURE_TENANT_ID_DEV }}
      tenant-id-test: ${{ secrets.AZURE_TENANT_ID_TEST }}
      tenant-id-prod: ${{ secrets.AZURE_TENANT_ID_PROD }}
      subscription-id-dev: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
      subscription-id-test: ${{ secrets.AZURE_SUBSCRIPTION_ID_TEST }}
      subscription-id-prod: ${{ secrets.AZURE_SUBSCRIPTION_ID_PROD }}
