name: Test deployment playground pipeline.

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy-container-app:
    environment: dev
    name: Test stuff
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - id: get-branch-detail
      outputs:
        branch-name: ${{ case(github.head_ref == '', github.ref_name, github.head_ref) }}

    - run: |
        echo "${{ steps.jobs.get-branch-detail.outputs.branch-name }}"
        echo "${{ github.head_ref }}"
        echo "${{ github.ref_name }}"