name: Traveller service pipeline.

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  variables:
    name: Generate variables
    runs-on: ubuntu-latest
    steps:
    - uses: sming-code/get-version-no-action@v1
      id: get-version
      with:
        major: 1
        minor: 0
    - name: Display done
      run: echo "Variables loaded..."
    outputs:
      environment: dev
      logical-area: private
      service-name: traveller-svc
      version-no: ${{ steps.get-version.outputs.version-no }}
      last-release-tag: ${{ steps.get-version.outputs.last-release-tag }}
  ca-variables:
    name: Generate container app variables
    needs: [ variables ]
    uses: ./.github/workflows/get-ca-variables.yaml
    with:
      environment: ${{ needs.variables.outputs.environment }}
      logical-area: ${{ needs.variables.outputs.logical-area }}
      service-name: ${{ needs.variables.outputs.service-name }}
      version-no: ${{ needs.variables.outputs.version-no }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_DEV }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  output-for-test:
    name: Output for test
    needs: [ ca-variables ]
    runs-on: ubuntu-latest
    steps:
      - id: output-test
        run: |
          echo "${{ needs.ca-variables.outputs.resource-group-name }}"
          echo "${{ needs.ca-variables.outputs.resource-group-exists }}"
          echo "${{ needs.ca-variables.outputs.container-app-name }}"
          echo "${{ needs.ca-variables.outputs.container-app-exists }}"
          echo "${{ needs.ca-variables.outputs.sql-database-name }}"
          echo "${{ needs.ca-variables.outputs.sql-database-exists }}"

  get-app-managed-identity:
    name: Get existing or new app managed identity
    needs: [ variables ]
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/get-container-app-managed-identity.yaml
    with:
      environment: dev
      service-name: ${{ needs.variables.outputs.container-app-name }}
      logical-area: private
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  create-database:
    name: Create database for container app
    needs: [ variables ]
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/deploy-database.yaml
    with:
      env-name: dev
      service-name: ${{ needs.variables.outputs.container-app-name }}
      logical-area: private
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
