name: Create resource group

on:
  workflow_call:
    inputs:
      logical-area:
        description: The logical area of our ecosystem - i.e. public, private
        required: true
        type: string
      service-name:
        description: The name of the service
        required: true
        type: string
    outputs:
      sql-server-name:
        value: ${{ jobs.deploy-database.outputs.sql-server-name }}
      database-name:
        value: ${{ jobs.deploy-database.outputs.sql-database-name }}
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy-database:
    environment: dev
    name: Deploy new resource group to azure
    outputs:
      sql-server-name: ${{ steps.rg-deployment.outputs.sql_server_name }}
      sql-database-name: ${{ steps.rg-deployment.outputs.sql_database_name }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: azure/login@v3
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: deploy
      id: rg-deployment
      uses: azure/bicep-deploy@v2
      with:
        type: deployment
        operation: create
        name: deploy-database
        scope: resourceGroup
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resource-group-name: rg-dev-tag
        template-file: ./.github/workflows/bicep/create-database.bicep
        parameters: |
          env_name: dev
          logical_area: private
          service_name: traveller

    - run: |
        echo '${{ steps.rg-deployment.outputs.sql_server_name }}'
        echo '${{ steps.rg-deployment.outputs.sql_database_name }}'

    - add-user:
