name: Test deployment pipeline.

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy-to-dev:
        description: 'Deploy branch container to dev environment for testing'
        required: false
        type: boolean
        default: false

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  id-token: write
  contents: read

jobs:
  variables:
    name: Generate variables
    runs-on: ubuntu-latest
    steps:
    - uses: sming-code/get-version-no-action@v1
      id: get-version
      with:
        major: 1
        minor: 0
    - name: Display done
      run: echo "Variables loaded..."
    outputs:
      version-no: ${{ steps.get-version.outputs.version-no }}
      last-release-tag: ${{ steps.get-version.outputs.last-release-tag }}

  deployments:
    name: Deploy to environments
    runs-on: ubuntu-latest
    needs: [ variables ]
    env:
      logical-area: private
      service-name: traveller-svc
      version-no: ${{ needs.variables.outputs.version-no }}
      ghcr-username: ${{ secrets.GHCR_USERNAME }}
      ghcr-token: ${{ secrets.GHCR_TOKEN }}

    strategy:
      fail-fast: true
      matrix:
        environment:
          - dev
          - test
          - prod
      max-parallel: 1
    environment: ${{ matrix.environment }}
    steps:
    - uses: actions/checkout@v6

    - uses: azure/login@v3
      with:
        client-id: ${{ case(matrix.environment == 'dev', secrets.AZURE_CLIENT_ID_DEV, case(matrix.environment == 'test', secrets.AZURE_CLIENT_ID_TEST, case(matrix.environment == 'prod', secrets.AZURE_CLIENT_ID_PROD, 'unknows'))) }}
        tenant-id: ${{ case(matrix.environment == 'dev', secrets.AZURE_TENANT_ID_DEV, case(matrix.environment == 'test', secrets.AZURE_TENANT_ID_TEST, case(matrix.environment == 'prod', secrets.AZURE_TENANT_ID_PROD, 'unknows'))) }}
        subscription-id: ${{ case(matrix.environment == 'dev', secrets.AZURE_SUBSCRIPTION_ID_DEV, case(matrix.environment == 'test', secrets.AZURE_SUBSCRIPTION_ID_TEST, case(matrix.environment == 'prod', secrets.AZURE_SUBSCRIPTION_ID_PROD, 'unknows'))) }}

    - name: Generate container app variables
      id: ca-variables
      uses: ./.github/workflows/get-ca-variables.yaml
      with:
        environment: ${{ matrix.environment }}

    - id: output-test
      run: |
        echo "${{ steps.ca-variables.outputs.resource-group-name }}"
        echo "${{ steps.ca-variables.outputs.resource-group-exists }}"
        echo "${{ steps.ca-variables.outputs.container-app-environment-name }}"
        echo "${{ steps.ca-variables.outputs.container-app-name }}"
        echo "${{ steps.ca-variables.outputs.container-app-exists }}"
        echo "${{ steps.ca-variables.outputs.sql-server-name }}"
        echo "${{ steps.ca-variables.outputs.sql-database-name }}"
        echo "${{ steps.ca-variables.outputs.sql-database-exists }}"
        echo "${{ steps.ca-variables.outputs.environment-resource-group-name }}"

    - uses: ./.github/actions/deploy-container-app
      env:
        subscription: ${{ case(matrix.environment == 'dev', 'sub-tag-testing', case(matrix.environment == 'test', 'sub-tag-testing', case(matrix.environment == 'prod', 'sub-tag-testing', 'unknows'))) }}
        subscription-id: ${{ case(matrix.environment == 'dev', secrets.AZURE_SUBSCRIPTION_ID_DEV, case(matrix.environment == 'test', secrets.AZURE_SUBSCRIPTION_ID_TEST, case(matrix.environment == 'prod', secrets.AZURE_SUBSCRIPTION_ID_PROD, 'unknows'))) }}
        environment-resource-group-name: ${{ steps.ca-variables.outputs.environment-resource-group-name }}
        revision-suffix: ${{ needs.variables.outputs.version-no }}
        resource-group-name: ${{ steps.ca-variables.outputs.resource-group-name }}
        resource-group-exists: ${{ steps.ca-variables.outputs.resource-group-exists }}
        container-app-environment-name: ${{ steps.ca-variables.outputs.container-app-environment-name }}
        container-app-name: ${{ steps.ca-variables.outputs.container-app-name }}
        container-app-exists: ${{ steps.ca-variables.outputs.container-app-exists }}
        sql-server-name: ${{ steps.ca-variables.outputs.sql-server-name }}
        sql-database-name: ${{ steps.ca-variables.outputs.sql-database-name }}
        sql-database-exists: ${{ steps.ca-variables.outputs.sql-database-exists }}


  # ca-variables:
  #   name: Generate container app variables
  #   needs: [ variables ]
  #   uses: ./.github/workflows/get-ca-variables.yaml
  #   with:
  #     environment: ${{ needs.variables.outputs.environment }}
  #     logical-area: ${{ needs.variables.outputs.logical-area }}
  #     service-name: ${{ needs.variables.outputs.service-name }}
  #     version-no: ${{ needs.variables.outputs.version-no }}
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_DEV }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  # output-for-test:
  #   name: Output for test
  #   needs: [ ca-variables ]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - id: output-test
  #       run: |
  #         echo "${{ needs.ca-variables.outputs.resource-group-name }}"
  #         echo "${{ needs.ca-variables.outputs.resource-group-exists }}"
  #         echo "${{ needs.ca-variables.outputs.container-app-environment-name }}"
  #         echo "${{ needs.ca-variables.outputs.container-app-name }}"
  #         echo "${{ needs.ca-variables.outputs.container-app-exists }}"
  #         echo "${{ needs.ca-variables.outputs.sql-server-name }}"
  #         echo "${{ needs.ca-variables.outputs.sql-database-name }}"
  #         echo "${{ needs.ca-variables.outputs.sql-database-exists }}"
  #         echo "${{ needs.ca-variables.outputs.environment-resource-group-name }}"

  # deploy-container-app:
  #   env: 
  #   environment: ${{ inputs.environment }}
  #   name: Deploy container app to azure
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v6
  #   - uses: azure/login@v3
  #     with:
  #       client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #       tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #       subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # - uses: ./.github/actions/deploy-container-app
    #   with:
    #     subscription: sub-tag-testing
    #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #     environment: dev
    #     environment-resource-group-name: ${{ inputs.environment-resource-group-name }}
    #     revision-suffix: ${{ inputs.revision-suffix }}
    #     resource-group-name: ${{ inputs.resource-group-name }}
    #     resource-group-exists: ${{ inputs.resource-group-exists }}
    #     container-app-environment-name: ${{ inputs.container-app-environment-name }}
    #     container-app-name: ${{ inputs.container-app-name }}
    #     container-app-exists: ${{ inputs.container-app-exists }}
    #     sql-server-name: ${{ inputs.sql-server-name }}
    #     sql-database-name: ${{ inputs.sql-database-name }}
    #     sql-database-exists: ${{ inputs.sql-database-exists }}
    #     ghcr-username: ${{ secrets.GHCR_USERNAME }}
    #     ghcr-token: ${{ secrets.GHCR_TOKEN }}

  # deploy-dev:
  #   name: Deploy container app and related resources to dev
  #   needs: [ variables, ca-variables ]
  #   if: ${{ (github.ref == 'refs/heads/main') || (inputs.deploy-to-dev == true) }}
  #   uses: ./.github/workflows/deploy-container-app.yaml
  #   with:
  #     subscription: sub-tag-testing
  #     environment: dev
  #     environment-resource-group-name: ${{ needs.ca-variables.outputs.environment-resource-group-name }}
  #     revision-suffix: ${{ needs.variables.outputs.version-no }}
  #     resource-group-name: ${{ needs.ca-variables.outputs.resource-group-name }}
  #     resource-group-exists: ${{ needs.ca-variables.outputs.resource-group-exists }}
  #     container-app-environment-name: ${{ needs.ca-variables.outputs.container-app-environment-name }}
  #     container-app-name: ${{ needs.ca-variables.outputs.container-app-name }}
  #     container-app-exists: ${{ needs.ca-variables.outputs.container-app-exists }}
  #     sql-server-name: ${{ needs.ca-variables.outputs.sql-server-name }}
  #     sql-database-name: ${{ needs.ca-variables.outputs.sql-database-name }}
  #     sql-database-exists: ${{ needs.ca-variables.outputs.sql-database-exists }}
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_DEV }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
  #     GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
