name: Get container app variables

on:
  workflow_call:
    inputs:
      environment:
        description: The environment being deployed to
        required: true
        type: string
      logical-area:
        description: The logical area of our ecosystem - i.e. public, private
        required: true
        type: string
      service-name:
        description: The name of the service
        required: true
        type: string
      version-no:
        description: The version being built
        required: true
        type: string
    outputs:
      resource-group-name:
        value: ${{ jobs.build-ca-variables.outputs.resource-group-name }}
      resource-group-exists:
        value: ${{ jobs.build-ca-variables.outputs.resource-group-exists }}
      container-app-environment-name:
        value: ${{ jobs.build-ca-variables.outputs.container-app-environment-name }}
      container-app-name:
        value: ${{ jobs.build-ca-variables.outputs.container-app-name }}
      container-app-exists:
        value: ${{ jobs.build-ca-variables.outputs.container-app-exists }}
      sql-database-name:
        value: ${{ jobs.build-ca-variables.outputs.sql-database-name }}
      sql-database-exists:
        value: ${{ jobs.build-ca-variables.outputs.sql-database-exists }}
      environment-resource-group-name:
        value: rg-${{ inputs.environment }}-tag
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  build-ca-variables:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    outputs:
      resource-group-name: ${{ steps.calculate.outputs.RESOURCE_GROUP_NAME }}
      resource-group-exists: ${{ steps.calculate.outputs.RESOURCE_GROUP_EXISTS }}
      container-app-environment-name: ${{ steps.calculate.outputs.CONTAINER_APP_ENVIRONMENT_NAME }}
      container-app-name: ${{ steps.calculate.outputs.CONTAINER_APP_NAME }}
      container-app-exists: ${{ steps.calculate.outputs.CONTAINER_APP_EXISTS }}
      sql-database-name: ${{ steps.calculate.outputs.SQL_DATABASE_NAME }}
      sql-database-exists: ${{ steps.calculate.outputs.SQL_DATABASE_EXISTS }}
    steps:
    - uses: actions/checkout@v6
    - uses: azure/login@v3
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: calculate-variables
      id: calculate
      run: |
        serviceEnvironment="$Service_Name-$Environment"
        branchName="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
        branchSuffix="$([[ $branchName =~ ^(feature|bugfix)\/([A-Z]{3}-[0-9]{3})-.+$ ]] && echo -${BASH_REMATCH[2],,} || echo '')"
        containerAppEnvironmentName="caenv-$Environment-tag-$Logical_Area"
        containerAppName="ca-$serviceEnvironment$branchSuffix"
        resourceGroupName="rg-$containerAppName"
        sqlDatabaseName="sql-$containerAppName"
        environmentResourceGroupResponse="$(az group list --query '[?name==`'rg-$Environment-tag'`].name')"
        resourceGroupResponse="$(az group list --query '[?name==`'$resourceGroupName'`].name')"
        resourceGroupExists="$([[ $resourceGroupResponse == '[]' ]] && echo 0 || echo 1)"
        sqlDatabaseId="$(az sql db list -s dev-tag -g rg-dev-tag --query '[?name==`'$sqlDatabaseName'`].id | [0]')"
        sqlDatabaseExists="$([[ $sqlDatabaseId == '' ]] && echo 0 || echo 1)"
        if [[ $resourceGroupExists == 0 ]]; then
          containerAppId=""
          containerAppExists=0;
        else
          containerAppId="$(az containerapp list -g $resourceGroupName --query '[?name==`'$containerAppName'`].id | [0]')"
          containerAppExists="$([[ $containerAppId == '' ]] && echo 0 || echo 1)";
        fi
        echo "RESOURCE_GROUP_NAME=$resourceGroupName" >> $GITHUB_OUTPUT
        echo "RESOURCE_GROUP_EXISTS=$resourceGroupExists" >> $GITHUB_OUTPUT
        echo "CONTAINER_APP_ENVIRONMENT_NAME=$containerAppEnvironmentName" >> $GITHUB_OUTPUT
        echo "CONTAINER_APP_NAME=$containerAppName" >> $GITHUB_OUTPUT
        echo "CONTAINER_APP_EXISTS=$containerAppExists" >> $GITHUB_OUTPUT
        echo "SQL_DATABASE_NAME=$sqlDatabaseName" >> $GITHUB_OUTPUT
        echo "SQL_DATABASE_EXISTS=$sqlDatabaseExists" >> $GITHUB_OUTPUT
      env:
        Environment: ${{ inputs.environment }}
        Logical_Area: ${{ inputs.logical-area }}
        Service_Name: ${{ inputs.service-name }}
        Version_No: ${{ inputs.version-no }}
